### ISSUE TITLE
Build preset 'netlify-edge' throws error when used together with @sidebase/nuxt-auth

### ISSUE THREAD

**Issue by wireless25** [sidebase/sidebase#107]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.14.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@7.26.3
- Builder:          vite
- User Config:      modules, typescript, nitro
- Runtime Modules:  @sidebase/nuxt-auth@0.4.4
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/wireless25/sidebase-netlify-edge-reproduction

### Describe the bug

When 'netlify-edge' is selected as the build preset and the `@sidebase/nuxt-auth` module is active, the build fails. I also tried the Sidebase starter without the auth module, and the build completed fine.

### Additional context
- checkout reproduction repo
- install deps `pnpm i`
- `pnpm build`

### Logs

```shell
[10:28:03 PM]  ERROR  "createHash" is not exported by "node_modules/.pnpm/unenv@1.4.1/node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/.pnpm/jose@4.14.4/node_modules/jose/dist/node/esm/runtime/digest.js".

  at error (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
  at Module.error (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13884:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:12429:39)
  at ReturnValueScope.findVariable (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
  at Identifier.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:8127:40)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:9680:15)
  at MemberExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at MemberExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:9344:19)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:9680:15)
  at MemberExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at MemberExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:9344:19)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at CallExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:9680:15)
  at ArrowFunctionExpression.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at VariableDeclarator.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at VariableDeclaration.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5734:28)
  at Program.bind (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:5734:28)
  at Module.bindReferences (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13459:18)
  at Graph.sortModules (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24965:20)
  at Graph.build (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24849:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:25875:13
  at async catchUnfinishedHookActions (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:25022:16)
  at async rollupInternal (node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:25870:5)
  at async _build (node_modules/.pnpm/nitropack@2.4.1/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:2246:20)
  at async node_modules/.pnpm/nuxt@3.5.1_rpjxlqcfh7pz5woobnsyir5gdu/node_modules/nuxt/dist/index.mjs:2492:9
  at async build (node_modules/.pnpm/nuxt@3.5.1_rpjxlqcfh7pz5woobnsyir5gdu/node_modules/nuxt/dist/index.mjs:3394:5)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.5.1/node_modules/nuxi/dist/chunks/build.mjs:56:5)
  at async _main (node_modules/.pnpm/nuxi@3.5.1/node_modules/nuxi/dist/cli.mjs:48:20)

 ELIFECYCLE  Command failed with exit code 1.
```
```

**Comment by wireless25** [comment]
Nevermind, just realised, that next-auth can not run serverless/on the edge, so Sidebase has no problem. Maybe a hint in the docs could help.
