### ISSUE TITLE
npm install fails when choosing TailwindCSS during setup

### ISSUE THREAD

**Issue by ashantyk** [sidebase/sidebase#111]
### Environment

Windows 11 Pro
Node 18.18.0
NPM 9.8.1

### Reproduction

npm create sidebase@latest

>> stack: Merino
>> modules: Prisma ORM, nuxt-auth, tRPC 10, Tailwind CSS, Naive UI
>> git init: no
>> CI: GitHub Actions

npm install

### Describe the bug

> postinstall
> nuxt prepare

i nuxt-auth setup starting                                                                          nuxt-auth 22:24:24
√ nuxt-auth setup done                                                                              nuxt-auth 22:24:24
i Using default Tailwind CSS file                                                            nuxt:tailwindcss 22:24:24

 ERROR  Cannot read properties of undefined (reading 'push')                                                  22:24:25

  at /D:/Other/mf/node_modules/@huntersofbook/naive-ui-nuxt/dist/module.mjs:35:38
  at /D:/Other/mf/node_modules/hookable/dist/index.mjs:48:66
  at Object.run (/D:/Other/mf/node_modules/hookable/dist/index.mjs:41:43)
  at /D:/Other/mf/node_modules/hookable/dist/index.mjs:48:56
  at async writeTypes (/D:/Other/mf/node_modules/@nuxt/kit/dist/index.mjs:2898:3)
  at async Object.run (/D:/Other/mf/node_modules/nuxi/dist/chunks/prepare.mjs:68:5)
  at async runCommand$1 (/D:/Other/mf/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1647:7)
  at async runCommand$1 (/D:/Other/mf/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1638:11)
  at async runMain$1 (/D:/Other/mf/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1770:7)

 ERROR  Cannot read properties of undefined (reading 'push')                                                  22:24:25

npm ERR! code 1
npm ERR! path D:\Other\mf
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c nuxt prepare

**Comment by ashantyk** [comment]
it seems that bumping up the tailwindcss version in package.json to ^6.8.0 fixes the issue, at first glance.

**Comment by mkitzmann** [comment]
Same Problem here

MacOS 12.4
node 18.12
npm 8.19.2

npm create sidebase@latest

        stack: Merino
        modules: Prisma ORM, tRPC 10, Tailwind CSS, Naive UI
        git init: yes
        CI: GitHub Actions

npm install

**Comment by joe-irving** [comment]
Same error on `yarn install`

Ubuntu 20.04.6 LTS
node 18.12.0
yarn 1.22.19

creating sidebase went okay, then yarn install came with this error;

```
$ nuxt prepare
ℹ nuxt-auth setup starting                                                                                                                                                                                   nuxt-auth 21:35:49
✔ nuxt-auth setup done                                                                                                                                                                                       nuxt-auth 21:35:49

 ERROR  Cannot read properties of undefined (reading 'push')                                                                                                                                                            21:35:50

  at node_modules/@huntersofbook/naive-ui-nuxt/dist/module.mjs:35:38
  at node_modules/hookable/dist/index.mjs:48:66
  at Object.run (node_modules/hookable/dist/index.mjs:41:43)
  at node_modules/hookable/dist/index.mjs:48:56
  at async writeTypes (node_modules/@nuxt/kit/dist/index.mjs:2898:3)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:68:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1770:7) 



 ERROR  Cannot read properties of undefined (reading 'push')                                                                                                                                                            21:35:50

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by joe-irving** [comment]
BTW I got this install to work by changing to using  [Cheviot](https://sidebase.io/sidebase/welcome/stacks#cheviot)
